/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        xs: "480px",
      },
      fontFamily: {
        sans: ["var(--font-body)", "Inter", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        serif: ["Georgia", "Cambria", "Times New Roman", "serif"],
      },
      colors: {
        fem: {
          bg: "#0B0C10",
          card: "#12151C",
          surface: "#181C26",
          border: "#202533",
          red: "#E1251B",
          flame: "#FF4538",
          orange: "#FA5D29",
          amber: "#F59E0B",
          cyan: "#00D2FF",
          emerald: "#10B981",
          muted: "#94A3B8",
          subtle: "#64748B",
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        femdark: {
          primary: "#E1251B",
          "primary-focus": "#C81E15",
          "primary-content": "#FFFFFF",
          secondary: "#FA5D29",
          accent: "#00D2FF",
          neutral: "#12151C",
          "neutral-focus": "#181C26",
          "base-100": "#0B0C10",
          "base-200": "#111319",
          "base-300": "#1E222D",
          "base-content": "#F8FAFC",
          info: "#00D2FF",
          success: "#10B981",
          warning: "#F59E0B",
          error: "#FF4538",
        },
        smartdark: {
          primary: "#E1251B",
          secondary: "#FA5D29",
          accent: "#00D2FF",
          neutral: "#12151C",
          "base-100": "#0B0C10",
          "base-200": "#111319",
          "base-300": "#1E222D",
          "base-content": "#F8FAFC",
          info: "#00D2FF",
          success: "#10B981",
          warning: "#F59E0B",
          error: "#FF4538",
        },
        smartlight: {
          primary: "#E1251B",
          secondary: "#FA5D29",
          accent: "#00D2FF",
          neutral: "#1E293B",
          "base-100": "#FFFFFF",
          "base-200": "#F8FAFC",
          "base-300": "#E2E8F0",
          "base-content": "#0F172A",
          info: "#0EA5E9",
          success: "#10B981",
          warning: "#F59E0B",
          error: "#EF4444",
        },
      },
    ],
    darkTheme: "femdark",
  },
};
